### ISSUE TITLE
Про нищебродское администрирование

### ISSUE THREAD

**Issue by dimbor-ru** [bambrman/yota#4]
Приветствую.
Сначала о термине: Под оным администрированием понимается организация резервного канала из конторы с помощью йотовского свистка, воткнутого в сервер.  Далее на сервере поднимается ssh туннель до своего VPS. В этот туннель пробрасывается серверный 22 порт. Теперь можно цепляться к серверу при падении основного канала. Слово "нищебродское" появилось, т.к. халявных 64K (для москвы POS-MA4-001) вполне себе достаточно для работы в консоли.

Все бы ничего, но периодически случается относительно долгая недоступность основного канала. Тогда напрашивается выставление портов публичных сервисов на тот же VPS. Хочется скорости. Но наказывать себя месячной оплатой не хочется. По счастью, есть 2 часа и сутки на максимальной скорости (PO-TURBO-MA4-01 и PO-TURBO-MA4-02) но скриптом они от чего-то не включаются. Скрипт сгенерирован с помощью gen.sh и туда добавлены в case эти тарифы.

Скажите, есть идеи, почему сие действо (не) присходит? Или же мне нужно пройти весь квест, гачиная с fire-bug?

**Comment by dimbor-ru** [comment]
Ответа не дождался, покрутил сам. 
Во первых халявные 64K надо включать каждые (сутки?) посылом без авторизации POST "accept_lte=1&redirurl=http%3A%2F%2Fwww.yota.ru%2F
city=msk&connection_type=light&service_id=Sliders_Free_Temp" на http://hello.yota.ru/php/go.php Критерием случившегося отключения может быть отлов принудительного redirurl с любого сайта на http://hello.yota.ru. Но можно проще: пинг внешнего хоста начинает выдавать экзотическое "Destination Port Unreachable".

Во вторых раскрыл тайну включения двух часов и суток. Оно вот так после логина:
search to id:  name="resourceId" value="id_here" where
      name="CurrentDevice" value="1" in same <form></form> block

 https://my.yota.ru/selfcare/devices/enableOption
 1)    POST    id=?????&force=&optionOfferCode=PO-TURBO-MA4-01
       check   {"status":"ok","message":"Вы подключены на 2 часа на максимальной скорости за 50 руб."}
 2)    POST    id=?????&force=on&optionOfferCode=PO-TURBO-MA4-01
       check   {"status":"ok","message":"Вы подключены на 2 часа на максимальной скорости за 50 руб."}

Там походу схема логина еще другая - предварительным запросом получается лицевой счет и фигурирует при логине. Пока детально не разобрался, т.к. любое неловкое движение стоит полтинника и потерянных двух часов.

**Comment by bambrman** [comment]
Скорее всего поменялся код личного кабинета йоты
