### ISSUE TITLE
cat: flag: Нет такого файла или каталога

### ISSUE THREAD

**Issue by mindw00rk** [bambrman/yota#5]
kost@Saturn ~/yota $ **./pingsh.sh** 
PING 192.168.1.111 (192.168.1.111) 56(84) bytes of data.
64 bytes from 192.168.1.111: icmp_seq=1 ttl=64 time=0.066 ms

--- 192.168.1.111 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.066/0.066/0.066/0.000 ms
aps is here
**cat: flag: Нет такого файла или каталога**
А что не так?

**Comment by bambrman** [comment]
По какой то причине не создается файл flag, возможно нет прав. Попробуйте создать вручную файл flag в каталоге со скриптом

**Comment by mindw00rk** [comment]
Раздал 777, все заработало! Спасибо за скрипты)
